[projects."/Users/kevinmhk/workspaces/hk_startup_setup"]
trust_level = "trusted"

[projects."/Users/kevinmhk/workspaces/program_trade_ib"]
trust_level = "trusted"

[projects."/Users/kevinmhk/workspaces/zsh_chezmoi_status_welcome_message"]
trust_level = "trusted"

# User is never prompted: if the command fails, Codex will automatically try
# something out. Note the `exec` subcommand always uses this mode.
approval_policy = "never"

# same as `--sandbox danger-full-access`
sandbox_mode = "danger-full-access"

[projects."/Users/kevinmhk/workspaces"]
trust_level = "trusted"


# [tools]
# web_search = true


[features]
unified_exec = true
shell_snapshot = true
web_search_request = true
view_image_tool = true
skills = true
steer = true
